export const ActionTypes = {
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    SET_EMPLOYEES : "SET_EMPLOYEES",
    SELECTED_EMPLOYEE : "SELECTED_EMPLOYEE",
    REMOVE_SELECTED_EMPLOYEE : "REMOVE_SELECTED_EMPLOYEE",
    UPDATE_EMPLOYEE:"UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE:"DELETE_EMPLOYEE"
};